Repository algosup/2024-2025-project-3-quickest-path-team-6, pull requests merged in 2025-02, with the labels that each got.

#69 Documents into Main
  Documents/Functional/functionalSpecifications.md
  Documents/Management/WeeklyReports/weeklyReport3.md
  Documents/Management/WeeklyReports/weeklyReport4.md
  Documents/Technical/technicalSpecifications.md
  Documents/TestPlan/TestingTools/test.csv
  Documents/TestPlan/testCases.md
  Documents/TestPlan/testPlan.md
  README.md
Labels: documentation, enhancement, high, management, technical, functional, test plan/cases

#71 First stable version release
  .gitignore
  Src/Client/Bin/pathQuick.exe
  Src/Client/Display/display.hpp
  Src/Client/Input/userInput.hpp
  Src/Client/includes/includes.hpp
  Src/Client/main.cpp
  Src/Client/request.hpp
  Src/Client/startClient.cmd
  Src/Server/Algorithm/algorithm.cpp
  Src/Server/Algorithm/loadData.cpp
  Src/Server/Algorithm/loadData.hpp
  Src/Server/Api/api.cpp
  Src/Server/Api/api.hpp
  Src/Server/Api/server.cpp
  Src/Server/Bin/dataValidation.exe
  Src/Server/Bin/server
  Src/Server/Bin/server.exe
  Src/Server/DataValidation/validateCsv.cpp
  Src/Server/Formatting/conversionJson.hpp
  Src/Server/Formatting/conversionXml.hpp
  Src/Server/Includes/includes.hpp
  Src/Server/startServer.cmd
  Src/Server/startServer.sh
  Src/Server/startValidation.cmd
  Src/Server/startValidation.sh
Labels: enhancement, high, dev

#72 Updating README documentation
  README.md
Labels: documentation, enhancement

#76 Second stable version
  Src/Client/Display/display.hpp
  Src/Client/startClient.sh
  Src/Server/Algorithm/loadData.hpp
  Src/Server/Api/api.cpp
  Src/Server/Api/server.cpp
  Src/Server/DataValidation/validateCsv.cpp
  Src/Server/startServer.sh
  Src/UnitTesting/startUnitTests.sh
  Src/unitTesting/Bin/pathQuick.json
  Src/unitTesting/Bin/server.exe
  Src/unitTesting/Bin/unitTesting.exe
  Src/unitTesting/csv/correct.csv
  Src/unitTesting/csv/incorrect.csv
  Src/unitTesting/display.hpp
  Src/unitTesting/startUnitTests.cmd
  Src/unitTesting/tests/dataValidationTest.hpp
  Src/unitTesting/tests/pathingTest.hpp
  Src/unitTesting/tests/serverTest.hpp
  Src/unitTesting/unitTesting.cpp
  Src/unitTesting/unitTesting.hpp
Labels: enhancement, medium, dev
