Repository algosup/2024-2025-project-3-quickest-path-team-6, pull requests merged in 2025-01, with the labels that each got.

#6 Added self-hosted runner
  .github/workflows/main.yml
Labels: enhancement, high, dev

#9 Created console display + algorithm's basis + JSON and XML format handling
  .gitignore
  Src/Algorithm/algorithm.cpp
  Src/Algorithm/loadData.cpp
  Src/Bin/pathQuick
  Src/Bin/pathQuick.json
  Src/Bin/pathQuick.xml
  Src/Bin/quickPath
  Src/Headers/Display/display.hpp
  Src/Headers/Formatting/convertionJson.hpp
  Src/Headers/Formatting/convertionXml.hpp
  Src/Headers/Input/userInput.hpp
  Src/Input/userInput.hpp
  Src/Libraries/Tinyxml2/tinyxml2.cpp
  Src/Libraries/Tinyxml2/tinyxml2.h
  Src/Libraries/nlohmann/adl_serializer.hpp
  Src/Libraries/nlohmann/detail/conversions/from_json.hpp
  Src/Libraries/nlohmann/detail/conversions/to_chars.hpp
  Src/Libraries/nlohmann/detail/conversions/to_json.hpp
  Src/Libraries/nlohmann/detail/exceptions.hpp
  Src/Libraries/nlohmann/detail/input/binary_reader.hpp
  Src/Libraries/nlohmann/detail/input/input_adapters.hpp
  Src/Libraries/nlohmann/detail/input/json_sax.hpp
  Src/Libraries/nlohmann/detail/input/lexer.hpp
  Src/Libraries/nlohmann/detail/input/parser.hpp
  Src/Libraries/nlohmann/detail/input/position_t.hpp
  Src/Libraries/nlohmann/detail/iterators/internal_iterator.hpp
  Src/Libraries/nlohmann/detail/iterators/iter_impl.hpp
  Src/Libraries/nlohmann/detail/iterators/iteration_proxy.hpp
  Src/Libraries/nlohmann/detail/iterators/iterator_traits.hpp
  Src/Libraries/nlohmann/detail/iterators/json_reverse_iterator.hpp
  Src/Libraries/nlohmann/detail/iterators/primitive_iterator.hpp
  Src/Libraries/nlohmann/detail/json_pointer.hpp
  Src/Libraries/nlohmann/detail/json_ref.hpp
  Src/Libraries/nlohmann/detail/macro_scope.hpp
  Src/Libraries/nlohmann/detail/macro_unscope.hpp
  Src/Libraries/nlohmann/detail/meta/cpp_future.hpp
  Src/Libraries/nlohmann/detail/meta/detected.hpp
  Src/Libraries/nlohmann/detail/meta/is_sax.hpp
  Src/Libraries/nlohmann/detail/meta/type_traits.hpp
  Src/Libraries/nlohmann/detail/meta/void_t.hpp
  Src/Libraries/nlohmann/detail/output/binary_writer.hpp
  Src/Libraries/nlohmann/detail/output/output_adapters.hpp
  Src/Libraries/nlohmann/detail/output/serializer.hpp
  Src/Libraries/nlohmann/detail/value_t.hpp
  Src/Libraries/nlohmann/json.hpp
  Src/Libraries/nlohmann/json_fwd.hpp
  Src/Libraries/nlohmann/thirdparty/hedley/hedley.hpp
  Src/Libraries/nlohmann/thirdparty/hedley/hedley_undef.hpp
  Src/main.cpp
  Src/start.cmd
  Src/start.sh
Labels: enhancement, critical, dev

#21 1st stable version of the program
  .gitignore
  README.md
  Src/Client/Bin/pathQuick
  Src/Client/Bin/pathQuick.json
  Src/Client/Bin/pathQuick.xml
  Src/Client/Display/display.hpp
  Src/Client/Input/userInput.hpp
  Src/Client/main.cpp
  Src/Client/request.hpp
  Src/Client/startClient.cmd
  Src/Client/startClient.sh
  Src/Libraries/Tinyxml2/tinyxml2.cpp
  Src/Libraries/Tinyxml2/tinyxml2.h
  Src/Libraries/nlohmann/adl_serializer.hpp
  Src/Libraries/nlohmann/detail/conversions/from_json.hpp
  Src/Libraries/nlohmann/detail/conversions/to_chars.hpp
  Src/Libraries/nlohmann/detail/conversions/to_json.hpp
  Src/Libraries/nlohmann/detail/exceptions.hpp
  Src/Libraries/nlohmann/detail/input/binary_reader.hpp
  Src/Libraries/nlohmann/detail/input/input_adapters.hpp
  Src/Libraries/nlohmann/detail/input/json_sax.hpp
  Src/Libraries/nlohmann/detail/input/lexer.hpp
  Src/Libraries/nlohmann/detail/input/parser.hpp
  Src/Libraries/nlohmann/detail/input/position_t.hpp
  Src/Libraries/nlohmann/detail/iterators/internal_iterator.hpp
  Src/Libraries/nlohmann/detail/iterators/iter_impl.hpp
  Src/Libraries/nlohmann/detail/iterators/iteration_proxy.hpp
  Src/Libraries/nlohmann/detail/iterators/iterator_traits.hpp
  Src/Libraries/nlohmann/detail/iterators/json_reverse_iterator.hpp
  Src/Libraries/nlohmann/detail/iterators/primitive_iterator.hpp
  Src/Libraries/nlohmann/detail/json_pointer.hpp
  Src/Libraries/nlohmann/detail/json_ref.hpp
  Src/Libraries/nlohmann/detail/macro_scope.hpp
  Src/Libraries/nlohmann/detail/macro_unscope.hpp
  Src/Libraries/nlohmann/detail/meta/cpp_future.hpp
  Src/Libraries/nlohmann/detail/meta/detected.hpp
  Src/Libraries/nlohmann/detail/meta/is_sax.hpp
  Src/Libraries/nlohmann/detail/meta/type_traits.hpp
  Src/Libraries/nlohmann/detail/meta/void_t.hpp
  Src/Libraries/nlohmann/detail/output/binary_writer.hpp
  Src/Libraries/nlohmann/detail/output/output_adapters.hpp
  Src/Libraries/nlohmann/detail/output/serializer.hpp
  Src/Libraries/nlohmann/detail/value_t.hpp
  Src/Libraries/nlohmann/json.hpp
  Src/Libraries/nlohmann/json_fwd.hpp
  Src/Libraries/nlohmann/thirdparty/hedley/hedley.hpp
  Src/Libraries/nlohmann/thirdparty/hedley/hedley_undef.hpp
  Src/Server/Algorithm/algorithm.cpp
  Src/Server/Algorithm/loadData.cpp
  Src/Server/Api/api.cpp
  Src/Server/Api/api.hpp
  Src/Server/Api/server.cpp
  Src/Server/Bin/server
  Src/Server/Formatting/conversionJson.hpp
  Src/Server/Formatting/conversionXml.hpp
  Src/Server/startServer.cmd
  Src/Server/startServer.sh
  Src/main.cpp
  Src/pathQuickLauncher.cmd
  Src/pathQuickLauncher.sh
Labels: enhancement, high, dev

#22 Update optimized algorithm branch
  Src/Bin/pathQuick
  Src/Bin/pathQuick.exe
  Src/Bin/pathQuick.json
  Src/Bin/pathQuick.xml
  Src/Bin/server
  Src/Bin/server.exe
  Src/Client/Bin/pathQuick
  Src/Client/Bin/pathQuick.json
  Src/Client/Bin/pathQuick.xml
  Src/Client/Display/display.hpp
  Src/Client/Input/userInput.hpp
  Src/Client/main.cpp
  Src/Client/request.hpp
  Src/Client/startClient.cmd
  Src/Client/startClient.sh
  Src/Server/Algorithm/algorithm.cpp
  Src/Server/Algorithm/loadData.cpp
  Src/Server/Api/api.cpp
  Src/Server/Api/api.hpp
  Src/Server/Api/server.cpp
  Src/Server/Bin/server
  Src/Server/Formatting/conversionJson.hpp
  Src/Server/Formatting/conversionXml.hpp
  Src/Server/startServer.cmd
  Src/Server/startServer.sh
  Src/pathQuickLauncher.cmd
  Src/pathQuickLauncher.sh
  Src/start.cmd
  Src/start.sh
  Src/startServer.cmd
  Src/startServer.sh
Labels: enhancement, medium, dev

#18 Adding functional specifications, technical specifications and management documents in main branch
  Documents/Functional/functionalSpecifications.md
  Documents/Management/WeeklyReports/weeklyReport1.md
  Documents/Management/WeeklyReports/weeklyReport2.md
  Documents/Management/WeeklyReports/weeklyReport3.md
  Documents/Management/WeeklyReports/weeklyReport4.md
  Documents/Management/WeeklyReports/weeklyReport5.md
  Documents/Management/WeeklyReports/weeklyReport6.md
  Documents/Management/managementArtifacts.md
  Documents/Management/projectCharter.md
  Documents/Manuals/userManual.md
  Documents/Technical/conventions.md
  Documents/Technical/technicalSpecifications.md
  Documents/TestPlan/testCases.md
  Documents/TestPlan/testPlan.md
  README.md
Labels: documentation, enhancement, management, technical, functional, test plan/cases

#25 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement, dev

#30 Updating dev branch with optimized algorithm
  .gitignore
  Src/Client/Bin/pathQuick.exe
  Src/Client/Display/display.hpp
  Src/Client/Input/userInput.hpp
  Src/Client/includes/includes.hpp
  Src/Client/main.cpp
  Src/Client/request.hpp
  Src/Client/startClient.cmd
  Src/Server/Algorithm/algorithm.cpp
  Src/Server/Algorithm/loadData.cpp
  Src/Server/Api/api.cpp
  Src/Server/Api/api.hpp
  Src/Server/Api/server.cpp
  Src/Server/Bin/server.exe
  Src/Server/DataValidation/validateCsv.cpp
  Src/Server/Formatting/conversionJson.hpp
  Src/Server/Formatting/conversionXml.hpp
  Src/Server/startServer.cmd
  Src/Server/startServer.sh
  Src/Server/startValidation.cmd
  Src/Server/startValidation.sh
Labels: enhancement, dev
